#!/bin/bash

# bspwm startup script. Intended to be run from an xsession configuration
# to run bspwm and some associated programs.
# 
# Author: Diego Berrocal

# Load X resources (fixes some font issues)
xrdb -merge .Xresources &

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
# xcompmgr -n &
# compton &

###############################
### LOAD SCREEN BACKGROUNDS ###
###############################
nautilus &

#
# STARTUP ICON TRAY
#

# We are using stalonetray to create a small icon tray at the
# top right of the screen. You are likely to want to tweak the
# size of the icons and the width of the tray based upon the
# size of your screen and your xmobar configuration. The goal is
# to make stalonetray look like it is part of xmobar.
# 
# Line by line, the options used by default below mean:
# - icons should be aligned with the "East" or right side of the tray
# - the width of the tray should be 5 icons wide by one icon tall, and it 
#   should be located 0 pixels from the right of the screen (-0) and 0 pixels
#   from the top of the screen (+0).
# - By setting our maximum geometry to the same thing, the tray will not grow.
# - The background color of the tray should be black.
# - This program should not show up in any taskbar.
# - Icons should be set to size "24".
# - Kludges argument of "force_icons_size" forces all icons to really, truly 
#   be the size we set.
# - window-strut "none" means windows are allowed to cover the tray. In
#   other words, trust xmonad to handle this part.
#
stalonetray \
    --icon-gravity E \
    --geometry 9x1-0+0 \
    --max-geometry 9x1-0+0 \
    --background '#1a1a1a' \
    --skip-taskbar \
    --icon-size 24 \
    --kludges force_icons_size \
    --window-strut none \
&



# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Synaptics
syndaemon -i 1 -t &

# Start xFlux
# xflux -l 51.503 -g -0.1276


#Plz low screen brightness
xbacklight -set 50

dropbox start &
# megasync &

################################################################################
############## START OF APPLICATIONS ###########################################
################################################################################


# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

export TERM=rxvt-unicode-256color

# I disabled my touchpad because I hate those things. You can find the id
# of a device you want to disable using "xinput list"; unfortunately it can
# change depending on what devices you have plugged into USB. We extract the
# id of the device from the output of xinput, then use it to disable the
# device
TOUCHPAD_ID=`xinput | grep 'Touchpad' | cut -f 2 | cut -f 2 -d =`
xinput set-prop $TOUCHPAD_ID "Device Enabled" 1

# Remap caps lock to left control. This is not strictly speaking
# bspwm related, but it's handy if you're an emacs user.
setxkbmap -option 'ctrl:no caps'

# Check first if variety is Installed
if [ -z "$(pgrep variety)" ] ; then
    /opt/extras.ubuntu.com/variety/bin/variety &
fi

if [ -z "$(pgrep emacs)" ] ; then
    emacs &
fi

# mopidy &

pkill nautilus

ibus exit
