#!/bin/bash

export BSPWM_SOCKET=/tmp/bspwm-socket

#bspc monitor -d "α" "β" "γ" "δ" "ε" "ζ"
bspc monitor -d "i" "ii" "iii" "iv" "v" "vi"

bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

desktop_config() {
	bspc config $1 $2
	for M in $(bspc query -M); do
		bspc config -m $M $1 $2
	done
}

desktop_config border_width 1
desktop_config window_gap 20

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focus_follows_pointer false
## Bspwm window border colors
bspc config focused_border_color        "#d0d0d0"
bspc config normal_border_color         "#555555"
bspc config active_border_color         "#5C5955"
bspc config focused_locked_border_color "#00C7D8"
bspc config normal_locked_border_color  "#708D8F"
bspc config active_locked_border_color  "#808C8D"
bspc config urgent_border_color         "#C04747"
bspc config presel_border_color         "#00adca"

bspc config auto_alternate true
bspc config auto_cancel true
#bspc config normal_border_color "#cccccc"
#bspc config focused_border_color "#333333"
#bspc config presel_border_color "#cc6666"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0

# Rules
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a gimp floating=on
bspc rule -a scratchpad floating=on

# Exec on start
bspc config wm_name LG3D
floatpipe
wmname LG3D
