#!/bin/sh

fg="#FFeddcd3"
bg="#FF181512"
font1="Source Code Pro"
font2="-adobe-Source Code Pro-bold-normal-normal-*-16-*-*-*-m-0-fontset-auto1"

cd $(dirname $0)

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
echo "T" >  "$PANEL_FIFO" &
conky -c ./panel_conky > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | ./panel_bar | bar -g x15  -f "$font2","$font1" -F "$fg" -B "$bg" -u 1 &

wait
